sed -i '/#include/s|gdal/||' backend/wbpublic/grtui/geom_draw_box.h backend/wbpublic/grt/spatial_handler.h &&
install -D $SOURCE_CACHE/antlr-3.4-complete.jar linux-res/bin/antlr-3.4-complete.jar &&
default_cmake_build
